export const PAGE_CLEAR = 'CLEAR_PAGE';
export const PAGE_FETCH_REQUEST = 'PAGE_FETCH_REQUEST';
export const PAGE_FETCH_RECEIVE = 'PAGE_FETCH_RECEIVE';
export const PAGE_FETCH_FAILURE = 'PAGE_FETCH_FAILURE';
